In [1]:
from hyptorch.lorentz.layers.LEmbed import LorentzEmbedding
from hyptorch.lorentz.manifold import CustomLorentz 
import torch
import torch.nn as nn



/Users/admin/miniconda3/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [60]:

manifold = CustomLorentz()

input = torch.LongTensor([[ 4, 3, 2, 9, 123]])
l_emb = LorentzEmbedding(manifold=manifold, num_embeddings=1000, embedding_dim=3, padding_idx=0)
emb = nn.Embedding(num_embeddings=1000, embedding_dim=3, padding_idx=0)
l_out = l_emb(input)
out= emb(input)



In [61]:
manifold.origin((1,3))

Tensor on Lorentz manifold containing:
tensor([[1., 0., 0.]])

In [74]:
print(out)
print(l_out)

print(manifold.norm(out, dim=0))
print(manifold.norm(l_out, dim=0))

tensor([[[-1.4005, -1.3181,  0.4317],
         [ 2.6061,  0.9356,  1.6772],
         [-0.7892,  0.5192,  0.9778],
         [ 1.8911,  0.1575, -0.4635],
         [ 0.0970,  0.0519,  0.3939]]], grad_fn=<EmbeddingBackward0>)
tensor([[[ 1.5211, -0.5358, -1.0133],
         [ 1.5426, -1.1682,  0.1221],
         [ 1.4821, -0.0048,  1.0939],
         [ 1.4343,  0.3159,  0.9784],
         [ 1.5332,  0.3450, -1.1098]]], grad_fn=<EmbeddingBackward0>)
tensor([[1.0000e-04, 1.0000e-04, 7.7653e-01, 1.0000e-04, 3.8525e-01]],
       grad_fn=<SqrtBackward0>)
tensor([[1.0000e-04, 1.0000e-04, 1.0000e-04, 1.0000e-04, 1.0000e-04]],
       grad_fn=<SqrtBackward0>)
